// AUTO-GENERATED by typescript-type-def

export type ColumnType=("Isrc"|"Upc"|"NetEarnings");
export type Action=("Unique"|"Sum");
export type Column={"kind":ColumnType;"enabled":boolean;"name":string;"action":Action;};
export type Usize=number;
export type ColumnConfig=({"Name":string;}|{"Index":Usize;}|{"NameAtIndex":[string,Usize];}|{"CustomValue":string;});
export type ColumnLocation=({"Name":string;}|{"Index":Usize;}|{"NameAtIndex":[string,Usize];});
export type FilterOperator=("Is"|"IsNot");
export type FilterConfig={"column":ColumnLocation;"operator":FilterOperator;"value":string;};
export type SourceConfig={"header_row_index":Usize;"isrc":(ColumnConfig|null);"upc":(ColumnConfig|null);"revenue":(ColumnConfig|null);"filters":(FilterConfig)[];};
export type SourceType=({"id":"Landr";}|{"id":"Pretzel";}|{"id":"RepostBySoundCloud";}|{"id":"Stem";}|{"id":"Symphonic";}|{"id":"Custom";"content":SourceConfig;});
export type Source={"name":string;"files":(string)[];"kind":SourceType;};
export type Project={"columns":(Column)[];"sources":(Source)[];};
// AUTO-GENERATED by typescript-type-def

export type OpenedInfo={"path":(string|null);};
