[package]
name = "pivoteer"
version = "0.0.0"
edition = "2021"

[dependencies]
csv = "1.2"
bigdecimal = { version = "0.4", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
csv-pipeline = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
regex = "1.9"
rayon = "1.7"
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "4.3", features = ["derive"] }
dirs-next = "2.0"
deser-hjson = "2.2"
pretty_assertions = "1.4.1"
json5 = "1.3.1"
serde_path_to_error = "0.1.20"

[profile.dev]
opt-level = 1
